### ISSUE TITLE
Support text messages with stamps

### ISSUE THREAD

**Issue by igrep** [iij-ii/direct-hs#14]
I learned stamps could be attached to text messages:

![gif](https://user-images.githubusercontent.com/227057/42794725-60c478f6-89bb-11e8-89a8-388e73cf295a.gif)

But [current `Stamp` value constructor](https://github.com/iij-ii/direct-hs/blob/198401d7f652cdf065705ba1841957340b4e6d6c/src/Web/Direct/Types.hs#L176) doesn't support this feature.

**Comment by kazu-yamamoto** [comment]
Implemented.
